# Generated by Django 5.0.1 on 2024-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='no-photo.svg', null=True, upload_to=''),
        ),
    ]
