# Generated by Django 5.0.3 on 2024-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pastevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(default='no-photo.svg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='lote',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
